### ISSUE TITLE
Throws error if no settings are passed

### ISSUE THREAD

**Issue by guanzo** [Breci/twitch-ext-vuex#7]
This errors: 
```js
Vue.use(ExtensionPlugin, { store })
```

This does not error:
```js
Vue.use(ExtensionPlugin, { store, settings: {} })
```

![](https://i.gyazo.com/adec86bf41dab7693c0950edc5479bee.png)

**Comment by Breci** [comment]
fixed in https://github.com/Breci/twitch-ext-vuex/commit/e851f39fb664498a7fe34c99e1a9de66d36aacb6
